version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./wp_test_data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306:3306'
    expose:
      - '3306'
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8081:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WP_DEBUG_LOG: 1
    volumes:
      - './wp_test_data/uploads/:/var/www/html/wp-content/uploads'
